In [12]:
import os                               
import math                             
import numpy as np                    
import pandas as pd                     
import matplotlib.pyplot as plt       
from matplotlib import cm               
from mpl_toolkits.mplot3d import Axes3D

In [13]:
stocks = [stock.split('.')[0] for stock in sorted(os.listdir("/home/ananya/Ananya/Portfolio_optmization"))]
#stocks
print(stocks)

['A2M', 'AGL', 'ALL', 'ALQ', 'ALU', 'ALX', 'AMC', 'AMP', 'ANN', 'ANZ', 'APA', 'APT', 'AST', 'ASX', 'AWC', 'AZJ', 'BEN', 'BHP', 'BLD', 'BOQ', 'BPT', 'BSL', 'BXB', 'CAR', 'CBA', 'CCL', 'CGF', 'CHC', 'CIM', 'COH', 'COL', 'CPU', 'CSL', 'CTX', 'CWN', 'CWY', 'DMP', 'DOW', 'DXS', 'EVN', 'FBU', 'FLT', 'FMG', 'FPH', 'GMG', 'GOZ', 'GPT', 'HVN', 'IAG', 'IEL', 'ILU', 'IPL', 'JBH', 'JHX', 'LLC', 'MFG', 'MGR', 'MPL', 'MQG', 'NAB', 'NCM', 'NST', 'ORG', 'ORI', 'OSH', 'QAN', 'QBE', 'QUB', 'REA', 'RHC', 'RIO', 'RMD', 'S32', 'SAR', 'SCG', 'SEK', 'SGP', 'SGR', 'SHL', 'SKI', 'SOL', 'SPK', 'STO', 'SUN', 'SVW', 'SYD', 'TAH', 'TCL', 'TLS', 'TPM', 'TWE', 'VCX', 'VEA', 'WBC', 'WES', 'WOR', 'WOW', 'WPL', 'WTC', 'XRO']

In [14]:
from azure.quantum import Workspace
workspace = Workspace (
    subscription_id = "6e02aef9-2670-4418-92b8-7659cf5605d2",
    resource_group = "azurequantum",
    name = "workspace1",
    location = "japaneast"
)

In [15]:
dates = pd.date_range('2000-01-01', '2020-03-31') 
data = pd.DataFrame({'Time': dates})  
print(data)

           Time
0    2000-01-01
1    2000-01-02
2    2000-01-03
3    2000-01-04
4    2000-01-05
...         ...
7391 2020-03-27
7392 2020-03-28
7393 2020-03-29
7394 2020-03-30
7395 2020-03-31

[7396 rows x 1 columns]

In [16]:
for stock in stocks:
    prices = pd.read_csv("/home/ananya/Ananya/Portfolio_optmization/"+stock+".csv", usecols=['Date', 'Adj Close']
                        )
    #print(prices)
    prices['Date'] = pd.to_datetime(prices['Date'])  
    #print(prices)
    prices.rename(                                                            
        columns={"Date": "Time", "Adj Close": stock},
        inplace=True
    )
    
    data = pd.merge(data,prices)                                                               
    #print(data)

In [17]:
data = data[data['Time'].dt.weekday < 5] 
data = data.dropna(axis=0, how='all') 
data.head()

,Time,A2M,AGL,ALL,ALQ,ALU,ALX,AMC,AMP,ANN,...,TWE,VCX,VEA,WBC,WES,WOR,WOW,WPL,WTC,XRO
0,2018-11-21,9.35,17.038509,24.460472,6.933038,20.987122,6.371757,12.503032,2.359322,21.896090,...,12.983171,2.437163,1.736595,23.984272,29.940374,12.926534,27.647896,29.297903,15.383970,36.669998
1,2018-11-22,9.90,17.185871,25.325384,6.952164,20.780499,6.371757,12.418805,2.378983,22.098564,...,13.722596,2.446291,1.750829,24.068626,29.340820,12.868826,27.686203,29.492359,15.773060,37.389999
2,2018-11-23,9.76,17.222712,25.199049,6.942601,20.918247,6.390664,12.503032,2.418305,21.992508,...,14.116316,2.464547,1.798277,24.406036,29.874800,12.820737,28.002232,29.723852,15.952638,37.290001
3,2018-11-26,9.58,17.056931,25.014404,6.588777,20.760818,6.466293,12.624693,2.349492,21.828600,...,13.607361,2.473675,1.883683,24.321684,29.509445,12.387929,28.011808,29.047890,16.331751,37.139999
4,2018-11-27,9.75,17.379282,25.412848,6.770471,21.055996,6.551380,12.484315,2.388813,22.185339,...,13.799419,2.482802,1.845725,24.630978,29.668701,12.609141,28.346994,29.121971,16.970255,37.500000

In [18]:
p = data .drop(['Time'], axis=1).tail(1).to_numpy()
p

array([[ 16.6     ,  17.190001,  21.35    ,   5.56    ,  28.59    ,
          5.51    ,  13.04    ,   1.335   ,  27.190001,  16.959999,
         10.26    ,  18.799999,   1.71    ,  77.089996,   1.46    ,
          4.23    ,   6.27    ,  28.98    ,   2.05    ,   5.      ,
          1.15    ,   8.63    ,  10.56    ,  11.75    ,  61.82    ,
          8.84    ,   4.      ,   6.86    ,  23.25    , 187.449997,
         15.16    ,   9.71    , 296.679993,  22.32    ,   7.6     ,
          1.695   ,  51.099998,   2.98    ,   9.09    ,   3.82    ,
          3.24    ,   9.91    ,  10.      ,  28.84    ,  12.1     ,
          2.52    ,   3.63    ,   2.830808,   6.2     ,  11.56    ,
          6.98    ,   2.02    ,  28.      ,  18.52    ,  10.3     ,
         43.52    ,   2.09    ,   2.66    ,  85.75    ,  16.68    ,
         23.049999,  10.53    ,   4.38    ,  15.35    ,   2.38    ,
          3.23    ,   8.6     ,   2.15    ,  76.989998,  57.279999,
         84.57    ,  24.690001,   1.765   ,   3.67    ,   1.565   ,
         14.83    ,   2.53    ,   2.15    ,  24.33    ,   1.95    ,
         16.969999,   4.      ,   3.42    ,   9.13    ,  11.24    ,
          5.59    ,   2.53    ,  12.04    ,   3.07    ,   6.861685,
         10.03    ,   1.035   ,   1.27    ,  16.5     ,  34.27    ,
          6.15    ,  35.099998,  18.209999,  17.1     ,  67.910004]])

In [8]:
r = data[(data['Time'].dt.weekday == 4)& (data['Time'] >= '2019-01-01')] \
    .drop(['Time'], axis=1) \
    .pct_change(fill_method='ffill')
r

,A2M,AGL,ALL,ALQ,ALU,ALX,AMC,AMP,ANN,ANZ,...,TWE,VCX,VEA,WBC,WES,WOR,WOW,WPL,WTC,XRO
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,0.060396,0.024697,0.081395,0.075153,0.114478,0.041118,0.012898,0.049587,0.036262,0.040825,...,0.059201,0.043307,0.016667,0.023172,-0.004052,0.156304,0.011604,0.042307,0.161506,0.043032
39,0.097106,-0.012287,0.013333,0.011412,0.037980,-0.011058,0.002996,0.047244,0.037685,0.032884,...,0.032997,-0.011321,0.000000,0.021085,0.017214,0.014937,0.010796,0.018942,0.012023,-0.012424
44,-0.007660,0.036364,0.044143,0.021156,0.037422,0.039935,0.021658,-0.120301,0.011673,0.004603,...,0.010430,0.000000,-0.016394,-0.010325,0.010769,0.035320,0.018692,0.011508,0.048554,0.004035
48,0.047170,-0.004617,-0.007724,0.024862,0.005211,0.030722,0.008041,-0.042735,-0.002564,-0.048110,...,0.002581,-0.011450,0.016667,-0.050232,-0.019483,0.002843,-0.035387,-0.011669,0.018227,0.023641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,-0.013436,-0.072464,-0.115415,-0.154702,-0.099125,-0.041816,-0.061198,-0.186893,-0.050710,-0.088473,...,-0.079299,-0.080851,-0.068783,-0.084076,-0.102054,-0.094144,-0.107020,-0.137438,-0.216805,-0.156357
325,0.062905,-0.025601,-0.035941,-0.070574,-0.036039,-0.046135,-0.012504,-0.059701,-0.064865,-0.108337,...,-0.076777,0.000000,-0.042614,-0.096870,-0.035670,-0.059904,-0.008618,-0.055158,-0.003541,0.020638
330,-0.041489,-0.079357,-0.125627,-0.190476,-0.090603,-0.202614,-0.211087,-0.082540,-0.028902,-0.150858,...,-0.047000,-0.189815,-0.074184,-0.151288,-0.034439,-0.183517,-0.025000,-0.205080,-0.094478,0.069443
335,0.029281,-0.043681,-0.371551,-0.149444,-0.028889,-0.137705,0.072072,-0.093426,-0.184896,-0.147872,...,0.013641,-0.351429,-0.179487,-0.129691,-0.120740,-0.400624,0.011336,-0.237005,-0.132990,-0.231870
340,-0.018553,-0.029842,0.149943,0.007477,-0.008391,0.011407,0.053782,-0.030534,0.059334,-0.034332,...,-0.020704,-0.149780,-0.021774,-0.055802,-0.030949,0.005208,-0.071257,0.052500,0.228814,0.055870

In [9]:
mu = r.mean().to_numpy()
sigma = r.cov().to_numpy()

print(np.shape(sigma))
n=len(stocks)
print("The variance is:-\n",sigma)

(100, 100)
The variance is:-
 [[ 2.57428555e-03  4.84380474e-05  3.38228347e-04 ...  1.31444462e-04
  -3.79394806e-04  2.81591604e-04]
 [ 4.84380474e-05  8.72706369e-04  5.19041003e-04 ...  7.85229589e-04
   5.77111335e-04  4.76540534e-04]
 [ 3.38228347e-04  5.19041003e-04  4.05624983e-03 ...  2.49180775e-03
   2.21930441e-03  1.92093402e-03]
 ...
 [ 1.31444462e-04  7.85229589e-04  2.49180775e-03 ...  2.56249730e-03
   1.88403259e-03  1.58618522e-03]
 [-3.79394806e-04  5.77111335e-04  2.21930441e-03 ...  1.88403259e-03
   8.57997801e-03  2.24835455e-03]
 [ 2.81591604e-04  4.76540534e-04  1.92093402e-03 ...  1.58618522e-03
   2.24835455e-03  2.59250022e-03]]

In [10]:
from typing import List
from azure.quantum.optimization import Problem, ProblemType, Term

# mean= mu' * x
# mu' has a shape (1,100), x has a shape (100,1)
def objectiveFunction(mu)->Problem:
    terms=[]
    
    for i in range(0,n):
        
        terms.append(Term(c=mu[i] , indices=[i]))
    print(len(terms))
    #print(terms)
    return Problem(name="Portfolio Optimization problem" , problem_type=ProblemType.pubo, terms=terms)
        

# defining constraints
# x >= 0, variance <= threshold 
# variance = xT Î£x

In [31]:
def greaterThanZero(weight,x):
    for i in range(100):
        terms=[]
        if x[i]<0:
            terms.append(Term(c= weight, indices=[i]))

In [43]:
def threshold(sigma, treshold, x):
    
     xT = np.transpose(x)
     print(xT)

[[ 2.57428555e-03  4.84380474e-05  3.38228347e-04 ...  1.31444462e-04
  -3.79394806e-04  2.81591604e-04]
 [ 4.84380474e-05  8.72706369e-04  5.19041003e-04 ...  7.85229589e-04
   5.77111335e-04  4.76540534e-04]
 [ 3.38228347e-04  5.19041003e-04  4.05624983e-03 ...  2.49180775e-03
   2.21930441e-03  1.92093402e-03]
 ...
 [ 1.31444462e-04  7.85229589e-04  2.49180775e-03 ...  2.56249730e-03
   1.88403259e-03  1.58618522e-03]
 [-3.79394806e-04  5.77111335e-04  2.21930441e-03 ...  1.88403259e-03
   8.57997801e-03  2.24835455e-03]
 [ 2.81591604e-04  4.76540534e-04  1.92093402e-03 ...  1.58618522e-03
   2.24835455e-03  2.59250022e-03]]

In [11]:
from azure.quantum.optimization import ParallelTempering        
problem = objectiveFunction(mu)
#problem
solver = ParallelTempering(workspace)
solver.optimize(problem)

100
...

{'version': '1.0',
 'configuration': {'0': 0,
  '1': 1,
  '2': 0,
  '3': 1,
  '4': 0,
  '5': 1,
  '6': 0,
  '7': 1,
  '8': 0,
  '9': 1,
  '10': 0,
  '11': 0,
  '12': 0,
  '13': 0,
  '14': 1,
  '15': 0,
  '16': 1,
  '17': 1,
  '18': 1,
  '19': 1,
  '20': 1,
  '21': 1,
  '22': 0,
  '23': 0,
  '24': 1,
  '25': 0,
  '26': 1,
  '27': 1,
  '28': 1,
  '29': 0,
  '30': 0,
  '31': 1,
  '32': 0,
  '33': 1,
  '34': 1,
  '35': 0,
  '36': 0,
  '37': 1,
  '38': 1,
  '39': 0,
  '40': 1,
  '41': 1,
  '42': 0,
  '43': 0,
  '44': 0,
  '45': 1,
  '46': 1,
  '47': 0,
  '48': 1,
  '49': 0,
  '50': 0,
  '51': 1,
  '52': 0,
  '53': 0,
  '54': 0,
  '55': 0,
  '56': 1,
  '57': 0,
  '58': 1,
  '59': 1,
  '60': 0,
  '61': 0,
  '62': 1,
  '63': 1,
  '64': 1,
  '65': 1,
  '66': 1,
  '67': 1,
  '68': 0,
  '69': 1,
  '70': 0,
  '71': 0,
  '72': 1,
  '73': 0,
  '74': 1,
  '75': 1,
  '76': 1,
  '77': 1,
  '78': 0,
  '79': 1,
  '80': 1,
  '81': 0,
  '82': 1,
  '83': 1,
  '84': 0,
  '85': 0,
  '86': 1,
  '87': 0,
  '88': 0,
  '89': 0,
  '90': 1,
  '91': 1,
  '92': 1,
  '93': 1,
  '94': 0,
  '95': 1,
  '96': 0,
  '97': 1,
  '98': 0,
  '99': 0},
 'cost': -0.263543,
 'parameters': {'all_betas': {'segments': [{'type': 'constant',
     'value': 38.704319},
    {'type': 'constant', 'value': 648.145963},
    {'type': 'constant', 'value': 10853.909973},
    {'type': 'constant', 'value': 181760.542293},
    {'type': 'constant', 'value': 38.704319},
    {'type': 'constant', 'value': 111.359417},
    {'type': 'constant', 'value': 320.401449},
    {'type': 'constant', 'value': 921.853682},
    {'type': 'constant', 'value': 2652.341971},
    {'type': 'constant', 'value': 7631.273887},
    {'type': 'constant', 'value': 21956.573389},
    {'type': 'constant', 'value': 63173.08514},
    {'type': 'constant', 'value': 181760.542293},
    {'type': 'constant', 'value': 38.704319},
    {'type': 'constant', 'value': 74.165338},
    {'type': 'constant', 'value': 142.115855},
    {'type': 'constant', 'value': 272.32285},
    {'type': 'constant', 'value': 521.825906},
    {'type': 'constant', 'value': 999.924452},
    {'type': 'constant', 'value': 1916.058398},
    {'type': 'constant', 'value': 3671.557161},
    {'type': 'constant', 'value': 7035.449445},
    {'type': 'constant', 'value': 13481.350477},
    {'type': 'constant', 'value': 25833.00642},
    {'type': 'constant', 'value': 49501.288604},
    {'type': 'constant', 'value': 94854.525779},
    {'type': 'constant', 'value': 181760.542293},
    {'type': 'constant', 'value': 38.704319},
    {'type': 'constant', 'value': 61.907746},
    {'type': 'constant', 'value': 99.021741},
    {'type': 'constant', 'value': 158.385756},
    {'type': 'constant', 'value': 253.338788},
    {'type': 'constant', 'value': 405.216625},
    {'type': 'constant', 'value': 648.145963},
    {'type': 'constant', 'value': 1036.712622},
    {'type': 'constant', 'value': 1658.226884},
    {'type': 'constant', 'value': 2652.341971},
    {'type': 'constant', 'value': 4242.433891},
    {'type': 'constant', 'value': 6785.793654},
    {'type': 'constant', 'value': 10853.909973},
    {'type': 'constant', 'value': 17360.881824},
    {'type': 'constant', 'value': 27768.814965},
    {'type': 'constant', 'value': 44416.354676},
    {'type': 'constant', 'value': 71044.175461},
    {'type': 'constant', 'value': 113635.504393},
    {'type': 'constant', 'value': 181760.542293},
    {'type': 'constant', 'value': 38.704319},
    {'type': 'constant', 'value': 55.898519},
    {'type': 'constant', 'value': 80.731158},
    {'type': 'constant', 'value': 116.595572},
    {'type': 'constant', 'value': 168.392574},
    {'type': 'constant', 'value': 243.200136},
    {'type': 'constant', 'value': 351.240584},
    {'type': 'constant', 'value': 507.277463},
    {'type': 'constant', 'value': 732.632949},
    {'type': 'constant', 'value': 1058.101485},
    {'type': 'constant', 'value': 1528.157796},
    {'type': 'constant', 'value': 2207.034281},
    {'type': 'constant', 'value': 3187.498261},
    {'type': 'constant', 'value': 4603.528477},
    {'type': 'constant', 'value': 6648.623061},
    {'type': 'constant', 'value': 9602.240721},
    {'type': 'constant', 'value': 13867.988306},
    {'type': 'constant', 'value': 20028.772996},
    {'type': 'constant', 'value': 28926.455582},
    {'type': 'constant', 'value': 41776.889312},
    {'type': 'constant', 'value': 60336.064184},
    {'type': 'constant', 'value': 87140.059999},
    {'type': 'constant', 'value': 125851.597371},
    {'type': 'constant', 'value': 181760.542293},
    {'type': 'constant', 'value': 38.704319},
    {'type': 'constant', 'value': 52.347145}],
   'type': 'segments'},
  'seed': 2251498681,
  'sweeps': 10},
 'solutions': [{'configuration': {'0': 0,
    '1': 1,
    '2': 0,
    '3': 1,
    '4': 0,
    '5': 1,
    '6': 0,
    '7': 1,
    '8': 0,
    '9': 1,
    '10': 0,
    '11': 0,
    '12': 0,
    '13': 0,
    '14': 1,
    '15': 0,
    '16': 1,
    '17': 1,
    '18': 1,
    '19': 1,
    '20': 1,
    '21': 1,
    '22': 0,
    '23': 0,
    '24': 1,
    '25': 0,
    '26': 1,
    '27': 1,
    '28': 1,
    '29': 0,
    '30': 0,
    '31': 1,
    '32': 0,
    '33': 1,
    '34': 1,
    '35': 0,
    '36': 0,
    '37': 1,
    '38': 1,
    '39': 0,
    '40': 1,
    '41': 1,
    '42': 0,
    '43': 0,
    '44': 0,
    '45': 1,
    '46': 1,
    '47': 0,
    '48': 1,
    '49': 0,
    '50': 0,
    '51': 1,
    '52': 0,
    '53': 0,
    '54': 0,
    '55': 0,
    '56': 1,
    '57': 0,
    '58': 1,
    '59': 1,
    '60': 0,
    '61': 0,
    '62': 1,
    '63': 1,
    '64': 1,
    '65': 1,
    '66': 1,
    '67': 1,
    '68': 0,
    '69': 1,
    '70': 0,
    '71': 0,
    '72': 1,
    '73': 0,
    '74': 1,
    '75': 1,
    '76': 1,
    '77': 1,
    '78': 0,
    '79': 1,
    '80': 1,
    '81': 0,
    '82': 1,
    '83': 1,
    '84': 0,
    '85': 0,
    '86': 1,
    '87': 0,
    '88': 0,
    '89': 0,
    '90': 1,
    '91': 1,
    '92': 1,
    '93': 1,
    '94': 0,
    '95': 1,
    '96': 0,
    '97': 1,
    '98': 0,
    '99': 0},
   'cost': -0.263543}]}